export const ActionTypes = {
    CATEGORIES_LOADING: 'CATEGORIES_LOADING',
    SET_COMP_LOGO: 'SET_COMP_LOGO',
    SET_APP_TITLE: 'SET_APP_TITLE',
    SET_CATEGORIES: 'SET_CATEGORIES',
    SET_ENTRY_CATEGORY: 'SET_ENTRY_CATEGORY'
};